---
config-version: "1"
unit: MP
max-money: "1000000000"
default-money: "500"
ranking-op-enable: "false"
register: あなたのデータを登録しました。
money-received: '%pさんから%a%b受け取りました。'
command-check: 'あなたの所持金: %a%b'
command-view: '%p の所持金: %a%b'
command-pay: '%p に %a%b 支払いました。'
command-rank: 所持金ランキング
command-throw: '%a%b 捨てました。'
command-give: '%p の所持金を %a%b 増やしました。'
command-take: '%p の所持金を %a%b 減らしました。'
command-set: '%p の所持金を %a%b に設定しました。'
error-type: §c正しい形式で入力してください。/m help
error-not: §cそのプレイヤーは存在しません。
error-console: §cコンソールからは実行できません。
error-money: §c所持金が足りません。
error-per: §c権限者専用のコマンドです。
help:
  help-check: '/m check : 所持金確認'
  help-view: '/m view {プレイヤー} : プレイヤーの所持金確認'
  help-pay: '/m pay {プレイヤー} {金額} : プレイヤーに金額支払い'
  help-rank: '/m rank {ページ数} : 所持金ランキング'
  help-throw: '/m throw {金額} : 金額分所持金を捨てます。'
...
