name: MoneyPlusAPI
main: MP\MoneyPlusAPI
version: 2.0.5
load: POSTWORLD
author: gigantessbeta
description: Economy plugin.
api:
- 3.0.0
- 2.0.0
- 2.1.0
commands:
 m:
  description: MoneyPlus's command.
  usage: "Usage: /m {subcommand}"